### PR TITLE
Fix to compile with Visual C++ 16.11 and /Zc:implicitNoexcept-.

### PR DESCRIPTION
**Pull request by jaykrell**
Otherwise gets:
  Error C2694 'override': overriding virtual function
  has less restrictive exception specification than base
  class virtual member function 'base'

  Similar changes are being made e.g.:
    https://github.com/boostorg/json/pull/636

  And proposed here:
    https://github.com/boostorg/iostreams/pull/136

I grant there there could be more of this.
These two are just enough for our codebase.

### CODE REVIEW

**Comment by mclow** [comment]
Why would anyone want destructors to not be noexcept by default?

**Comment by jaykrell** [comment]
Our code is really not portable, very Windows-specific, fairly hopelessly so, and likely will remain that way for a very long time.
This is not the biggest problem by far.
If we really wanted portability in this regard, we'd run some large tool over our code and mark all destructors as noexcept(false), and pretend we got everything (i.e. ignoring third party code).

**Comment by jaykrell** [comment]
> whose exception specification will change from compiler to compiler

Isn't it the other way around? This tries to make the exception specification always the same?

**Comment by jeking3** [comment]
@jaykrell CI is working again, if you rebase it'll run everything now.
